namespace CurrieTechnologies.Blazor.WebAuthentication
{
    public enum AttestationConveyancePreference
    {
        /// <summary>
        ///  The relying party is not interested in this attestation.
        ///  This avoids making a check with the attestation certificate authority and asking the user consent for sharing identifying information.
        /// </summary>
        None,

        /// <summary>
        /// The client may change the assertion from the authenticator (for instance, using an anonymization CA).
        /// This value is used when the relying party wishes to verify the attestation.
        /// </summary>
        Indirect,

        /// <summary>
        /// The relying party wants to receive the attestation as generated by the authenticator.
        /// </summary>
        Direct
    }
}
